# 1. Logistic Regression

# Importing Libraries

In [68]:
import numpy as np
import pandas as pd

In [69]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [70]:
import matplotlib.pyplot as py

Matplotlib is building the font cache; this may take a moment.


# Uploading dataset

In [3]:
df = pd.read_csv("User_Data.csv")

In [4]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
df.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [20]:
x= df.iloc[:,[2,3]]
print(x)

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]


In [9]:
y = df.iloc[:,4]
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64


# Train Test Split

In [76]:
from sklearn.model_selection import train_test_split

In [128]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

# Standard Scaling

In [129]:
from sklearn.preprocessing import StandardScaler

In [130]:
st_x = StandardScaler()

In [131]:
x_train = st_x.fit_transform(x_train)

In [132]:
x_test = st_x.transform(x_test)

# Applying model

In [133]:
from sklearn.linear_model import LogisticRegression

In [134]:
lr = LogisticRegression()

In [135]:
lr.fit(x_train,y_train)

LogisticRegression()

In [136]:
y_pred = lr.predict(x_test)

In [137]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

# Checking Accuracy

In [138]:
from sklearn.metrics import confusion_matrix

In [139]:
cm = confusion_matrix(y_pred,y_test)

In [140]:
cm

array([[65,  8],
       [ 3, 24]], dtype=int64)

In [141]:
#as there is more value present in the digonal of the cm, therefore this model is suitable for prediction in this case.

# 2. KNN

In [142]:
from sklearn.neighbors import KNeighborsClassifier

In [143]:
classifier = KNeighborsClassifier(n_neighbors = 5, p=2, metric = "minkowski")

In [144]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [145]:
y_pred = classifier.predict(x_test)

In [146]:
cm = confusion_matrix(y_test,y_pred)

In [147]:
cm

array([[64,  4],
       [ 3, 29]], dtype=int64)

# 3. SVM

In [149]:
from sklearn.svm import SVC

In [151]:
svc = SVC(kernel = "linear")

In [152]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [154]:
y_pred = svc.predict(x_test)

In [155]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [156]:
from sklearn.metrics import accuracy_score

In [157]:
accuracy_score(y_test,y_pred)

0.9